baseURL = "https://bubobou.github.io/cabodoc/"
languageCode = "en-us"
title = "Documentation Carnet-de-Bord"
theme="geekdoc"
# Geekdoc required conÔ¨Åguration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo=false

# publish repository for  github
publishDir = "docs"


# Needed for mermaid shortcodes
[markup]
[markup.goldmark.renderer]
# Needed for mermaid shortcode
unsafe = true
[markup.tableOfContents]
startLevel = 1
endLevel = 9
